import type { NextPage } from "next";
import Head from "next/head";
import gql from "graphql-tag";

import { urqlClient } from "@/libs/gql-requests";
import { Output } from "@/types";
import { OutputRes } from "@/types/api";

type OutputProps = {
  outputs: Output[];
};

const Outputs: NextPage<OutputProps> = (props) => {
  console.log(props);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <main>body</main>
    </div>
  );
};

export const getServerSideProps = async () => {
  try {
    const client = await urqlClient();

    // 変数なしでGraphQL呼び出し
    const postsQuery = gql`
      query {
        getOutputs {
          id
          title
          image {
            url
            width
            height
          }
          page_url
          start_date
          end_date
          content
          front_end_info {
            repository_url
            skills
            content
            before_updates {
              title
              content
              skills
            }
          }
          back_end_info {
            repository_url
            skills
            content
            before_updates {
              title
              content
              skills
            }
          }
        }
      }
    `;
    const result = await client.query(postsQuery, {}).toPromise();
    const outputs = result.data.getOutputs as OutputRes[];

    const fetchOutputs = outputs.map((o) => {
      const { front_end_info, back_end_info } = o;

      return {
        id: o.id,
        title: o.title,
        image: o.image,
        pageUrl: o.page_url,
        startDate: o.start_date || "",
        endDate: o.end_date || "",
        content: o.content,
        frontEndInfo: {
          repositoryUrl: front_end_info.repository_url,
          skills: front_end_info.skills,
          content: front_end_info.content,
          beforeUpdates: front_end_info.before_updates,
        },
        backEndInfo: {
          repositoryUrl: back_end_info.repository_url,
          skills: back_end_info.skills,
          content: back_end_info.content,
          beforeUpdates: back_end_info.before_updates,
        },
      } as Output;
    });

    return {
      props: {
        outputs: fetchOutputs,
      },
    };
  } catch (e) {
    return {
      notFound: true,
    };
  }
};

export default Outputs;
