import type { NextPage } from "next";
import Head from "next/head";

const Output: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <main>body</main>
    </div>
  );
};

export default Output;
