import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import styled from "styled-components";

const Test = styled.div`
  color: red;
`;

const Home: NextPage = () => {
  console.log(process.env.MICROCMS_API_KEY);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Test>Smaple test</Test>
      <h1>test</h1>
      <ul>
        <li>test</li>
      </ul>
      <main>test</main>
    </div>
  );
};

export default Home;
