import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import styled from "styled-components";

type IndexProps = {
  title: string;
};

const Test = styled.div`
  color: red;
`;

const Home: NextPage<IndexProps> = (props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Test>Smaple test</Test>
      <h1>{props.title}</h1>
      <ul>
        <li>test</li>
      </ul>
      <main>test</main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps<IndexProps> = async () => {
  return {
    props: {
      title: "Hello, GraphQL!",
    },
  };
};

export default Home;
